### ISSUE TITLE
Curl does not support HTTP2

### ISSUE THREAD

**Issue by vjanssens** [cerberos-dev/crb-dock#49]
Currently, the installed `curl` extension does not support HTTP2 (which is required for requests to Apple Push Notification Service).

We found a way (cc @sjopet) to make it work in the workspace container, but we also need to make it work in the php-fpm container (as our php script is trying to call APNS).

Steps to reproduce
1. `docker-compose exec php-fpm bash`
1. `curl --http2 http://example.com/`

If this results in `curl: (1) Unsupported protocol`, HTTP2 is not setup correctly. 
If this returns HTML, everything is okay.

**Comment by vjanssens** [comment]
Please see branch `feature-curl-http2`. 

I think we need to integrate the changes from `workspace/Dockerfile-71` to marzun/basedock, as they already work.

php-fpm container still needs some work

**Comment by Mvzundert** [comment]
@vjanssens @sjopet Are you guys going to create a pull request or do we need to examine the branch?

**Comment by sjopet** [comment]
Ill make a pr for the changes we have, the php-fpm container has repository issues though and need some looking into to

**Comment by Mvzundert** [comment]
@sjopet What are the PHP-FPM repository issues?

**Comment by sjopet** [comment]
It doesn't have the right curl / http2 version
